package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE
var map_EgressFirewallDNSName = map[string]string{
	"":         "EgressFirewallDNSName describes a DNS name used in a EgressFirewall rule. It is TechPreviewNoUpgrade only.\n\nCompatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.",
	"metadata": "metadata is the standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata",
	"spec":     "spec is the specification of the desired behavior of the EgressFirewallDNSName.",
	"status":   "status is the most recently observed status of the EgressFirewallDNSName.",
}

func (EgressFirewallDNSName) SwaggerDoc() map[string]string {
	return map_EgressFirewallDNSName
}

var map_EgressFirewallDNSNameList = map[string]string{
	"":         "EgressFirewallDNSNameList contains a list of EgressFirewallDNSNames.\n\nCompatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.",
	"metadata": "metadata is the standard list's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata",
}

func (EgressFirewallDNSNameList) SwaggerDoc() map[string]string {
	return map_EgressFirewallDNSNameList
}

var map_EgressFirewallDNSNameSpec = map[string]string{
	"":     "EgressFirewallDNSNameSpec is a desired state description of EgressFirewallDNSName.",
	"name": "name is the DNS name used in a EgressFirewall rule.",
}

func (EgressFirewallDNSNameSpec) SwaggerDoc() map[string]string {
	return map_EgressFirewallDNSNameSpec
}

var map_EgressFirewallDNSNameStatus = map[string]string{
	"":              "EgressFirewallDNSNameStatus defines the observed status of EgressFirewallDNSName.",
	"resolvedNames": "resolvedNames contains a list of matching DNS names and their corresponding IP addresses along with TTL and last DNS lookup time.",
}

func (EgressFirewallDNSNameStatus) SwaggerDoc() map[string]string {
	return map_EgressFirewallDNSNameStatus
}

var map_EgressFirewallDNSNameStatusItem = map[string]string{
	"":               "EgressFirewallDNSNameStatusItem describes the details of a resolved DNS name.",
	"dnsName":        "dnsName is the resolved DNS name matching the name field of EgressFirewallDNSNameSpec.",
	"ips":            "The IP addresses associated with the DNS name used in a EgressFirewall rule.",
	"ttl":            "Minimum time-to-live value among all the IP addresses.",
	"lastLookupTime": "Timestamp when the last DNS lookup was successfully completed.",
	"retryCounter":   "retryCounter keeps the count of how many times the DNS lookup failed for the dnsName field.",
}

func (EgressFirewallDNSNameStatusItem) SwaggerDoc() map[string]string {
	return map_EgressFirewallDNSNameStatusItem
}

// AUTO-GENERATED FUNCTIONS END HERE
