// Code generated by protoc-gen-gogo.
// source: github.com/openshift/api/servicecertsigner/v1alpha1/generated.proto
// DO NOT EDIT!

/*
	Package v1alpha1 is a generated protocol buffer package.

	It is generated from these files:
		github.com/openshift/api/servicecertsigner/v1alpha1/generated.proto

	It has these top-level messages:
		DelegatedAuthentication
		DelegatedAuthorization
		ServiceCertSignerOperatorConfig
		ServiceCertSignerOperatorConfigSpec
		ServiceCertSignerOperatorConfigStatus
		ServiceServingCertSignerConfig
*/
package v1alpha1

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

func (m *DelegatedAuthentication) Reset()                    { *m = DelegatedAuthentication{} }
func (*DelegatedAuthentication) ProtoMessage()               {}
func (*DelegatedAuthentication) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{0} }

func (m *DelegatedAuthorization) Reset()                    { *m = DelegatedAuthorization{} }
func (*DelegatedAuthorization) ProtoMessage()               {}
func (*DelegatedAuthorization) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{1} }

func (m *ServiceCertSignerOperatorConfig) Reset()      { *m = ServiceCertSignerOperatorConfig{} }
func (*ServiceCertSignerOperatorConfig) ProtoMessage() {}
func (*ServiceCertSignerOperatorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptorGenerated, []int{2}
}

func (m *ServiceCertSignerOperatorConfigSpec) Reset()      { *m = ServiceCertSignerOperatorConfigSpec{} }
func (*ServiceCertSignerOperatorConfigSpec) ProtoMessage() {}
func (*ServiceCertSignerOperatorConfigSpec) Descriptor() ([]byte, []int) {
	return fileDescriptorGenerated, []int{3}
}

func (m *ServiceCertSignerOperatorConfigStatus) Reset()      { *m = ServiceCertSignerOperatorConfigStatus{} }
func (*ServiceCertSignerOperatorConfigStatus) ProtoMessage() {}
func (*ServiceCertSignerOperatorConfigStatus) Descriptor() ([]byte, []int) {
	return fileDescriptorGenerated, []int{4}
}

func (m *ServiceServingCertSignerConfig) Reset()      { *m = ServiceServingCertSignerConfig{} }
func (*ServiceServingCertSignerConfig) ProtoMessage() {}
func (*ServiceServingCertSignerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptorGenerated, []int{5}
}

func init() {
	proto.RegisterType((*DelegatedAuthentication)(nil), "github.com.openshift.api.servicecertsigner.v1alpha1.DelegatedAuthentication")
	proto.RegisterType((*DelegatedAuthorization)(nil), "github.com.openshift.api.servicecertsigner.v1alpha1.DelegatedAuthorization")
	proto.RegisterType((*ServiceCertSignerOperatorConfig)(nil), "github.com.openshift.api.servicecertsigner.v1alpha1.ServiceCertSignerOperatorConfig")
	proto.RegisterType((*ServiceCertSignerOperatorConfigSpec)(nil), "github.com.openshift.api.servicecertsigner.v1alpha1.ServiceCertSignerOperatorConfigSpec")
	proto.RegisterType((*ServiceCertSignerOperatorConfigStatus)(nil), "github.com.openshift.api.servicecertsigner.v1alpha1.ServiceCertSignerOperatorConfigStatus")
	proto.RegisterType((*ServiceServingCertSignerConfig)(nil), "github.com.openshift.api.servicecertsigner.v1alpha1.ServiceServingCertSignerConfig")
}
func (m *DelegatedAuthentication) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegatedAuthentication) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	if m.Disabled {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	return i, nil
}

func (m *DelegatedAuthorization) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegatedAuthorization) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	if m.Disabled {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	return i, nil
}

func (m *ServiceCertSignerOperatorConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ServiceCertSignerOperatorConfig) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.ObjectMeta.Size()))
	n1, err := m.ObjectMeta.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	dAtA[i] = 0x12
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.Spec.Size()))
	n2, err := m.Spec.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	dAtA[i] = 0x1a
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.Status.Size()))
	n3, err := m.Status.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n3
	return i, nil
}

func (m *ServiceCertSignerOperatorConfigSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ServiceCertSignerOperatorConfigSpec) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.OperatorSpec.Size()))
	n4, err := m.OperatorSpec.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n4
	dAtA[i] = 0x12
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.ServiceServingCertSignerConfig.Size()))
	n5, err := m.ServiceServingCertSignerConfig.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n5
	return i, nil
}

func (m *ServiceCertSignerOperatorConfigStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ServiceCertSignerOperatorConfigStatus) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.OperatorStatus.Size()))
	n6, err := m.OperatorStatus.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n6
	return i, nil
}

func (m *ServiceServingCertSignerConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ServiceServingCertSignerConfig) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.ServingInfo.Size()))
	n7, err := m.ServingInfo.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n7
	dAtA[i] = 0x12
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.Authentication.Size()))
	n8, err := m.Authentication.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n8
	dAtA[i] = 0x1a
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.Authorization.Size()))
	n9, err := m.Authorization.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n9
	dAtA[i] = 0x22
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.Signer.Size()))
	n10, err := m.Signer.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n10
	return i, nil
}

func encodeFixed64Generated(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Generated(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *DelegatedAuthentication) Size() (n int) {
	var l int
	_ = l
	n += 2
	return n
}

func (m *DelegatedAuthorization) Size() (n int) {
	var l int
	_ = l
	n += 2
	return n
}

func (m *ServiceCertSignerOperatorConfig) Size() (n int) {
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *ServiceCertSignerOperatorConfigSpec) Size() (n int) {
	var l int
	_ = l
	l = m.OperatorSpec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.ServiceServingCertSignerConfig.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *ServiceCertSignerOperatorConfigStatus) Size() (n int) {
	var l int
	_ = l
	l = m.OperatorStatus.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *ServiceServingCertSignerConfig) Size() (n int) {
	var l int
	_ = l
	l = m.ServingInfo.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Authentication.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Authorization.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Signer.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func sovGenerated(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *DelegatedAuthentication) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DelegatedAuthentication{`,
		`Disabled:` + fmt.Sprintf("%v", this.Disabled) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DelegatedAuthorization) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DelegatedAuthorization{`,
		`Disabled:` + fmt.Sprintf("%v", this.Disabled) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ServiceCertSignerOperatorConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ServiceCertSignerOperatorConfig{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(this.ObjectMeta.String(), "ObjectMeta", "k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "ServiceCertSignerOperatorConfigSpec", "ServiceCertSignerOperatorConfigSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "ServiceCertSignerOperatorConfigStatus", "ServiceCertSignerOperatorConfigStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ServiceCertSignerOperatorConfigSpec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ServiceCertSignerOperatorConfigSpec{`,
		`OperatorSpec:` + strings.Replace(strings.Replace(this.OperatorSpec.String(), "OperatorSpec", "github_com_openshift_api_operator_v1alpha1.OperatorSpec", 1), `&`, ``, 1) + `,`,
		`ServiceServingCertSignerConfig:` + strings.Replace(strings.Replace(this.ServiceServingCertSignerConfig.String(), "RawExtension", "k8s_io_apimachinery_pkg_runtime.RawExtension", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ServiceCertSignerOperatorConfigStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ServiceCertSignerOperatorConfigStatus{`,
		`OperatorStatus:` + strings.Replace(strings.Replace(this.OperatorStatus.String(), "OperatorStatus", "github_com_openshift_api_operator_v1alpha1.OperatorStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ServiceServingCertSignerConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ServiceServingCertSignerConfig{`,
		`ServingInfo:` + strings.Replace(strings.Replace(this.ServingInfo.String(), "HTTPServingInfo", "github_com_openshift_api_config_v1.HTTPServingInfo", 1), `&`, ``, 1) + `,`,
		`Authentication:` + strings.Replace(strings.Replace(this.Authentication.String(), "DelegatedAuthentication", "DelegatedAuthentication", 1), `&`, ``, 1) + `,`,
		`Authorization:` + strings.Replace(strings.Replace(this.Authorization.String(), "DelegatedAuthorization", "DelegatedAuthorization", 1), `&`, ``, 1) + `,`,
		`Signer:` + strings.Replace(strings.Replace(this.Signer.String(), "CertInfo", "github_com_openshift_api_config_v1.CertInfo", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *DelegatedAuthentication) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegatedAuthentication: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegatedAuthentication: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Disabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Disabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DelegatedAuthorization) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegatedAuthorization: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegatedAuthorization: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Disabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Disabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ServiceCertSignerOperatorConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ServiceCertSignerOperatorConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ServiceCertSignerOperatorConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ServiceCertSignerOperatorConfigSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ServiceCertSignerOperatorConfigSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ServiceCertSignerOperatorConfigSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorSpec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OperatorSpec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceServingCertSignerConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ServiceServingCertSignerConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ServiceCertSignerOperatorConfigStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ServiceCertSignerOperatorConfigStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ServiceCertSignerOperatorConfigStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorStatus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OperatorStatus.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ServiceServingCertSignerConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ServiceServingCertSignerConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ServiceServingCertSignerConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServingInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ServingInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authentication", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Authentication.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authorization", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Authorization.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Signer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGenerated(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGenerated = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("github.com/openshift/api/servicecertsigner/v1alpha1/generated.proto", fileDescriptorGenerated)
}

var fileDescriptorGenerated = []byte{
	// 686 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4d, 0x4f, 0x13, 0x4f,
	0x18, 0xef, 0x02, 0x21, 0xcd, 0x00, 0xcd, 0x3f, 0xf3, 0x57, 0x6c, 0x7a, 0x58, 0x4c, 0x8d, 0xc6,
	0x03, 0xcc, 0x0a, 0x18, 0x43, 0xb8, 0xb9, 0xe0, 0x5b, 0xd4, 0x60, 0xa6, 0x1c, 0x0c, 0x27, 0xa7,
	0xdb, 0xe9, 0x76, 0x80, 0xce, 0x6c, 0x76, 0xa6, 0x55, 0x39, 0x19, 0xe3, 0xc1, 0x83, 0x07, 0xbf,
	0x80, 0x27, 0x3f, 0x85, 0xdf, 0x80, 0x23, 0x47, 0x4e, 0x44, 0xd6, 0xaf, 0xe1, 0xc1, 0xec, 0xec,
	0xb4, 0xbb, 0x0b, 0xae, 0x6d, 0x6a, 0xbc, 0x75, 0x9e, 0xce, 0xf3, 0x7b, 0x79, 0x7e, 0xfb, 0x0c,
	0xd8, 0xf2, 0x99, 0xea, 0xf4, 0x9a, 0xc8, 0x13, 0x5d, 0x47, 0x04, 0x94, 0xcb, 0x0e, 0x6b, 0x2b,
	0x87, 0x04, 0xcc, 0x91, 0x34, 0xec, 0x33, 0x8f, 0x7a, 0x34, 0x54, 0x92, 0xf9, 0x9c, 0x86, 0x4e,
	0x7f, 0x95, 0x1c, 0x06, 0x1d, 0xb2, 0xea, 0xf8, 0x94, 0xd3, 0x90, 0x28, 0xda, 0x42, 0x41, 0x28,
	0x94, 0x80, 0xeb, 0x29, 0x08, 0x1a, 0x82, 0x20, 0x12, 0x30, 0x74, 0x09, 0x04, 0x0d, 0x40, 0x6a,
	0x2b, 0x19, 0x66, 0x5f, 0xf8, 0xc2, 0xd1, 0x58, 0xcd, 0x5e, 0x5b, 0x9f, 0xf4, 0x41, 0xff, 0x4a,
	0x38, 0x6a, 0x6b, 0x85, 0x42, 0x3d, 0xc1, 0xdb, 0xcc, 0x77, 0xfa, 0x97, 0x74, 0xd5, 0x36, 0x0b,
	0x7b, 0x44, 0x10, 0x5f, 0x14, 0xc5, 0x9e, 0x6a, 0x77, 0x0f, 0x36, 0x24, 0x62, 0x22, 0xbe, 0xdd,
	0x25, 0x5e, 0x87, 0x71, 0x1a, 0xbe, 0x75, 0x82, 0x03, 0x3f, 0x2e, 0x48, 0xa7, 0x4b, 0x15, 0xf9,
	0x1d, 0xa3, 0x53, 0xd4, 0x15, 0xf6, 0xb8, 0x62, 0x5d, 0x7a, 0xa9, 0xe1, 0xde, 0xa8, 0x06, 0xe9,
	0x75, 0x68, 0x97, 0x5c, 0xec, 0xab, 0x3f, 0x02, 0xd7, 0xb6, 0xe9, 0x21, 0xf5, 0xe3, 0xd2, 0xfd,
	0x9e, 0xea, 0x50, 0xae, 0x98, 0x47, 0x14, 0x13, 0x1c, 0x2e, 0x83, 0x72, 0x8b, 0x49, 0xd2, 0x3c,
	0xa4, 0xad, 0xaa, 0x75, 0xdd, 0xba, 0x5d, 0x76, 0xff, 0x3b, 0x3e, 0x5b, 0x2a, 0x45, 0x67, 0x4b,
	0xe5, 0x6d, 0x53, 0xc7, 0xc3, 0x1b, 0xf5, 0x87, 0x60, 0x31, 0x07, 0x24, 0x42, 0x76, 0x34, 0x09,
	0xce, 0x87, 0x69, 0xb0, 0xd4, 0x48, 0xd2, 0xde, 0xa2, 0xa1, 0x6a, 0xe8, 0xb4, 0x77, 0xcc, 0x98,
	0xb7, 0x74, 0x44, 0xf0, 0x15, 0x28, 0xc7, 0x83, 0x6b, 0x11, 0x45, 0x34, 0xe2, 0xdc, 0xda, 0x1d,
	0x94, 0xf8, 0x47, 0x59, 0xff, 0x28, 0x38, 0xf0, 0xe3, 0x82, 0x44, 0xf1, 0x6d, 0xd4, 0x5f, 0x45,
	0x3b, 0xcd, 0x7d, 0xea, 0xa9, 0xe7, 0x54, 0x11, 0x17, 0x1a, 0x0d, 0x20, 0xad, 0xe1, 0x21, 0x2a,
	0x3c, 0x02, 0x33, 0x32, 0xa0, 0x5e, 0x75, 0x4a, 0xa3, 0xbf, 0x44, 0x13, 0x7c, 0x98, 0x68, 0x84,
	0x8b, 0x46, 0x40, 0x3d, 0x77, 0xde, 0xa8, 0x98, 0x89, 0x4f, 0x58, 0x73, 0xc2, 0xf7, 0x16, 0x98,
	0x95, 0x8a, 0xa8, 0x9e, 0xac, 0x4e, 0x6b, 0xfa, 0xbd, 0x7f, 0x42, 0xaf, 0x19, 0xdc, 0x8a, 0x11,
	0x30, 0x9b, 0x9c, 0xb1, 0x61, 0xae, 0x7f, 0x9b, 0x02, 0x37, 0xc6, 0x30, 0x00, 0x43, 0x30, 0x3f,
	0xd8, 0x81, 0xf8, 0x6c, 0xe2, 0xd8, 0x28, 0x56, 0x3c, 0xb8, 0x9d, 0x0a, 0xdd, 0xc9, 0xf4, 0xbb,
	0x57, 0x8c, 0x9e, 0xf9, 0x6c, 0x15, 0xe7, 0x38, 0xe0, 0x17, 0x0b, 0xd8, 0xc6, 0xb8, 0x96, 0xc8,
	0xfd, 0x54, 0x62, 0x22, 0xcd, 0xe4, 0xb6, 0x52, 0xf8, 0x55, 0x98, 0xad, 0x40, 0x98, 0xbc, 0x7e,
	0xf0, 0x46, 0x51, 0x2e, 0x99, 0xe0, 0xee, 0x2d, 0xc3, 0x6d, 0x37, 0xfe, 0x08, 0x8e, 0x47, 0x90,
	0xd7, 0xbf, 0x5a, 0xe0, 0xe6, 0x58, 0xd3, 0x87, 0x47, 0xa0, 0x32, 0x74, 0x96, 0x24, 0x9e, 0xcc,
	0x6f, 0x73, 0xa2, 0xf9, 0x25, 0x89, 0x2e, 0x1a, 0x17, 0x95, 0x7c, 0x1d, 0x5f, 0x60, 0xaa, 0xff,
	0x9c, 0x06, 0x23, 0x8c, 0xc2, 0x7d, 0x30, 0x27, 0x93, 0xbf, 0x9e, 0xf0, 0xb6, 0x30, 0xda, 0xd6,
	0x8b, 0xb5, 0x25, 0x2f, 0x68, 0xbc, 0x68, 0x8f, 0x77, 0x77, 0x5f, 0x34, 0xd2, 0x56, 0xf7, 0x7f,
	0x23, 0x6a, 0x2e, 0x53, 0xc4, 0x59, 0x70, 0xf8, 0xc9, 0x02, 0x15, 0x92, 0x7b, 0x80, 0x4c, 0x88,
	0xcf, 0x26, 0xfa, 0xfa, 0x0b, 0x1e, 0xb5, 0x74, 0x3a, 0xf9, 0x3a, 0xbe, 0xc0, 0x0d, 0x3f, 0x5a,
	0x60, 0x81, 0x64, 0x9f, 0x31, 0xb3, 0x8b, 0x4f, 0xff, 0x5e, 0xcd, 0x10, 0xd2, 0xbd, 0x6a, 0xc4,
	0x2c, 0xe4, 0xca, 0x38, 0x4f, 0x0c, 0x77, 0xc1, 0x6c, 0x82, 0x57, 0x9d, 0xd1, 0x12, 0x96, 0xc7,
	0x09, 0x20, 0xce, 0x52, 0x4f, 0x3e, 0x5d, 0x70, 0x8d, 0x81, 0x0d, 0x96, 0x8b, 0x8e, 0xcf, 0xed,
	0xd2, 0xc9, 0xb9, 0x5d, 0x3a, 0x3d, 0xb7, 0x4b, 0xef, 0x22, 0xdb, 0x3a, 0x8e, 0x6c, 0xeb, 0x24,
	0xb2, 0xad, 0xd3, 0xc8, 0xb6, 0xbe, 0x47, 0xb6, 0xf5, 0xf9, 0x87, 0x5d, 0xda, 0x2b, 0x0f, 0x2c,
	0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xec, 0x26, 0x36, 0xe0, 0xe1, 0x07, 0x00, 0x00,
}
