apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
  name: machinesets.machine.openshift.io
spec:
  versions:
  - name: v1beta1
    subresources:
      scale:
        labelSelectorPath: .status.labelSelector
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
