compatibility:
  disabled: false
deepcopy:
  disabled: false
  headerFilePath: ../hack/empty.txt
  outputFileBaseName: zz_generated.deepcopy
schemacheck:
  disabled: false
  enabledValidators: []
  disabledValidators: []
schemapatch:
  disabled: false
  requiredFeatureSets:
  - ""
  - "Default"
  - "TechPreviewNoUpgrade"
  - "CustomNoUpgrade"
swaggerdocs:
  disabled: false
  commentPolicy: Warn
  outputFileName: zz_generated.swagger_doc_generated.go
