apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
  name: egressrouters.network.operator.openshift.io
spec:
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            oneOf:
            - properties:
                mode:
                  enum:
                  - Redirect
              required:
              - redirect
            properties:
              addresses:
                items:
                  properties:
                    gateway:
                      anyOf:
                      - format: ipv4
                      - format: ipv6
              networkInterface:
                oneOf:
                - required:
                  - macvlan
              redirect:
                properties:
                  fallbackIP:
                    anyOf:
                    - format: ipv4
                    - format: ipv6
                  redirectRules:
                    items:
                      properties:
                        destinationIP:
                          anyOf:
                          - format: ipv4
                          - format: ipv6
