apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/: "true"
  name: dnses.operator.openshift.io
spec:
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              upstreamResolvers:
                default: {}
                properties:
                  upstreams:
                    items:
                      anyOf:
                      - not:
                          required:
                          - address
                          - port
                        properties:
                          type:
                            enum:
                            - ""
                            - SystemResolvConf
                      - optional:
                        - port
                        properties:
                          type:
                            enum:
                            - Network
                        required:
                        - address
                      properties:
                        address:
                          anyOf:
                          - format: ipv4
                          - format: ipv6
