apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configs.imageregistry.operator.openshift.io
spec:
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              storage:
                properties:
                  oss:
                    properties:
                      encryption:
                        anyOf:
                        - not:
                            required:
                            - kms
                          properties:
                            method:
                              not:
                                enum:
                                - KMS
                        - properties:
                            method:
                              enum:
                              - KMS
                          required:
                          - kms
