// +build !ignore_autogenerated

// Code generated by openshift-compatibility-gen. DO NOT EDIT.

package v1

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *AllowAllPasswordIdentityProvider) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *AllowAllPasswordIdentityProvider) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *BasicAuthPasswordIdentityProvider) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *BasicAuthPasswordIdentityProvider) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *BuildDefaultsConfig) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *BuildDefaultsConfig) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *BuildOverridesConfig) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *BuildOverridesConfig) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *DefaultAdmissionConfig) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *DefaultAdmissionConfig) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *DenyAllPasswordIdentityProvider) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *DenyAllPasswordIdentityProvider) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *GitHubIdentityProvider) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *GitHubIdentityProvider) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *GitLabIdentityProvider) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *GitLabIdentityProvider) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *GoogleIdentityProvider) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *GoogleIdentityProvider) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *HTPasswdPasswordIdentityProvider) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *HTPasswdPasswordIdentityProvider) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *KeystonePasswordIdentityProvider) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *KeystonePasswordIdentityProvider) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *LDAPPasswordIdentityProvider) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *LDAPPasswordIdentityProvider) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *LDAPSyncConfig) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *LDAPSyncConfig) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *MasterConfig) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *MasterConfig) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *NodeConfig) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *NodeConfig) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *OpenIDIdentityProvider) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *OpenIDIdentityProvider) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *RequestHeaderIdentityProvider) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *RequestHeaderIdentityProvider) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *SessionSecrets) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *SessionSecrets) Exposed() bool {
	return false
}
