apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    api-approved.openshift.io: https://github.com/openshift/api/pull/2012
    api.openshift.io/merged-by-featuregates: "true"
    description: Provides summary information about an ongoing node pool update in
      Standalone clusters
    displayName: MachineConfigPoolProgressInsights
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  name: machineconfigpoolprogressinsights.update.openshift.io
spec:
  group: update.openshift.io
  names:
    kind: MachineConfigPoolProgressInsight
    listKind: MachineConfigPoolProgressInsightList
    plural: machineconfigpoolprogressinsights
    singular: machineconfigpoolprogressinsight
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: |-
          MachineConfigPoolProgressInsight provides summary information about an ongoing node pool update in Standalone clusters

          Compatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: |-
              spec is empty for now, MachineConfigPoolProgressInsight is purely status-reporting API. In the future spec may be used to hold
              configuration to drive what information is surfaced and how
            type: object
          status:
            description: status exposes the health and status of the ongoing cluster
              update
            properties:
              assessment:
                description: |-
                  assessment is a brief summary assessment of the pool update process. This value is human-oriented, and while it
                  looks like a state/phase enum, it is not meant to be used as such. Assessment is meant as human-oriented brief
                  summary matching the state expressed in conditions (taking into account various relations between them, like
                  ordering or precedence), intended to be directly used in UIs and reports. For machine-oriented conditional behavior
                  depending on the state, the conditions should be used instead.

                  The known values are: Pending, Completed, Degraded, Excluded, Progressing. The API is not restricted to these
                  values, and valid values can be even brief phrases, up to 64 characters long.
                maxLength: 64
                minLength: 1
                type: string
              completionPercent:
                description: completionPercent is a percentage of the pool update
                  completion (0-100)
                format: int32
                maximum: 100
                minimum: 0
                type: integer
              conditions:
                description: |-
                  conditions provide details about the machine config pool update. It contains at most 10 items. Known conditions are:
                  - Updating: whether the pool is updating; When Updating=False, the reason field can be Pending, Updated or Excluded
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                maxItems: 5
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              name:
                description: name is the name of the machine config pool
                maxLength: 64
                minLength: 1
                pattern: ^[a-z0-9-]+$
                type: string
              scopeType:
                description: scopeType describes whether the pool is a control plane
                  or a worker pool
                enum:
                - ControlPlane
                - WorkerPool
                type: string
              summaries:
                description: summaries is a list of counts of nodes matching certain
                  criteria (e.g. updated, degraded, etc.). Maximum 16 items can be
                  listed.
                items:
                  description: NodeSummary is a count of nodes matching certain criteria
                    (e.g. updated, degraded, etc.)
                  properties:
                    count:
                      description: count is the number of nodes matching the criteria,
                        between 0 and 2000
                      format: int32
                      maximum: 2000
                      minimum: 0
                      type: integer
                    type:
                      description: |-
                        type is the type of the summary. Valid values are: Total, Available, Progressing, Outdated, Draining, Excluded, Degraded
                        The summaries are not exclusive, a single node may be counted in multiple summaries.
                      enum:
                      - Total
                      - Available
                      - Progressing
                      - Outdated
                      - Draining
                      - Excluded
                      - Degraded
                      type: string
                  required:
                  - count
                  - type
                  type: object
                maxItems: 7
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
            required:
            - assessment
            - completionPercent
            - name
            - scopeType
            type: object
        required:
        - spec
        type: object
        x-kubernetes-validations:
        - message: When status is present, .status must match .metadata.name
          rule: '!has(self.status) || self.status.name == self.metadata.name'
    served: true
    storage: true
    subresources:
      status: {}
