apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    api-approved.openshift.io: https://github.com/openshift/api/pull/1300
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  name: ingresses.operator.openshift.io
spec:
  group: operator.openshift.io
  names:
    kind: Ingress
    listKind: IngressList
    plural: ingresses
    singular: ingress
  scope: Cluster
  versions:
    - name: v1
      storage: true
      served: true
      schema:
        openAPIV3Schema:
          description: "Ingress contains configuration options specific to the Ingress Operator itself. \n Compatibility level 1: Stable within a major release for a minimum of 12 months or 3 minor releases (whichever is longer)."
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: spec is the specification of the desired behavior of the Ingress Operator.
              type: object
              properties:
                operatorLogLevel:
                  description: 'operatorLogLevel is the log level of the ingress operator. Options are: * Normal * Debug * Trace * TraceAll When unspecified, the default level is "Normal".'
                  type: string
                  enum:
                    - ""
                    - Normal
                    - Debug
                    - Trace
                    - TraceAll
            status:
              description: status is the most recently observed status of the Ingress Operator.
              type: object
