apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/: "true"
  name: clustercsidrivers.operator.openshift.io
spec:
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          metadata:
            properties:
              name:
                enum:
                - ebs.csi.aws.com
                - efs.csi.aws.com
                - disk.csi.azure.com
                - file.csi.azure.com
                - filestore.csi.storage.gke.io
                - pd.csi.storage.gke.io
                - cinder.csi.openstack.org
                - csi.vsphere.vmware.com
                - manila.csi.openstack.org
                - csi.ovirt.org
                - csi.kubevirt.io
                - csi.sharedresource.openshift.io
                - diskplugin.csi.alibabacloud.com
                - vpc.block.csi.ibm.io
                - powervs.csi.ibm.com
                - secrets-store.csi.k8s.io
                - smb.csi.k8s.io
                type: string
