apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/: "true"
  name: kubecontrollermanagers.operator.openshift.io
spec:
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              managementState:
                pattern: ^(Managed|Force)$
          status:
            properties:
              nodeStatuses:
                items:
                  x-kubernetes-validations:
                  - fieldPath: .currentRevision
                    message: cannot be unset once set
                    rule: has(self.currentRevision) || !has(oldSelf.currentRevision)
                  - message: new node statuses may not set a revision
                    optionalOldSelf: true
                    rule: oldSelf.hasValue() || !(has(self.currentRevision) || has(self.targetRevision))
