// +build !ignore_autogenerated

// Code generated by openshift-compatibility-gen. DO NOT EDIT.

package v1

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
// Compatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.
func (in *BuildDefaultsConfig) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *BuildDefaultsConfig) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
// Compatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.
func (in *BuildOverridesConfig) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *BuildOverridesConfig) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
// Compatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.
func (in *OpenShiftAPIServerConfig) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *OpenShiftAPIServerConfig) Exposed() bool {
	return false
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
// Compatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.
func (in *OpenShiftControllerManagerConfig) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *OpenShiftControllerManagerConfig) Exposed() bool {
	return false
}
