apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: capabilities.config.openshift.io
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  group: config.openshift.io
  names:
    kind: Capability
    listKind: CapabilityList
    plural: capabilities
    singular: capability
  scope: Cluster
  preserveUnknownFields: false
  versions:
  - name: v1
    served: true
    storage: true
  subresources:
    status: {}
  "validation":
    "openAPIV3Schema":
      description: Capability holds the expected high-availability mode of the cluster.
        The canonical name is `cluster`
      type: object
      required:
      - spec
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: spec holds user settable values for configuration
          type: object
          properties:
            highAvailabilityMode:
              description: "HighAvailabilityMode express the high-availability expectations.
                \n The default is 'Full', which represents the behavior operators
                have in a \\\"normal\\\" cluster. The 'None' mode will be used in
                single-node deployments (developer and production) for example, and
                the operators should not configure the operand for highly-available
                operation \n Once set, this field cannot be changed."
              type: string
              default: Full
              enum:
              - Full
              - None
        status:
          description: status holds observed values from the cluster. They may not
            be overridden.
          type: object
