apiVersion: apiextensions.k8s.io/v1 # Hack because controller-gen complains if we don't have this
name: "[Stable] Infrastructure"
crd: 0000_10_config-operator_01_infrastructure-Default.crd.yaml
tests:
  onCreate:
  - name: Should be able to create a minimal Infrastructure
    initial: |
      apiVersion: config.openshift.io/v1
      kind: Infrastructure
      spec: {} # No spec is required for a Infrastructure
    expected: |
      apiVersion: config.openshift.io/v1
      kind: Infrastructure
      spec: {}
  onUpdate:
  - name: Should allow setting IBM Cloud NetworkResourceGroupName immutable status field
    initial: |
      apiVersion: config.openshift.io/v1
      kind: Infrastructure
      spec: {}
      status:
        controlPlaneTopology: "HighlyAvailable"
        infrastructureTopology: "HighlyAvailable"
    updated: |
      apiVersion: config.openshift.io/v1
      kind: Infrastructure
      spec: {}
      status:
        platformStatus:
          ibmcloud:
            networkResourceGroupName: bar
    expected: |
      apiVersion: config.openshift.io/v1
      kind: Infrastructure
      spec: {}
      status:
        controlPlaneTopology: "HighlyAvailable"
        infrastructureTopology: "HighlyAvailable"
        platformStatus:
          ibmcloud:
            networkResourceGroupName: bar
  - name: Should not allow changing IBM Cloud NetworkResourceGroupName immutable status field
    initial: |
      apiVersion: config.openshift.io/v1
      kind: Infrastructure
      spec: {}
      status:
        platformStatus:
          ibmcloud:
            networkResourceGroupName: foo
    updated: |
      apiVersion: config.openshift.io/v1
      kind: Infrastructure
      spec: {}
      status:
        platformStatus:
          ibmcloud:
            networkResourceGroupName: bar
    expectedStatusError: "status.platformStatus.ibmcloud.networkResourceGroupName: Invalid value: \"string\": NetworkResourceGroupName is immutable"
