apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/: "true"
  name: infrastructures.config.openshift.io
spec:
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              platformSpec:
                properties:
                  vsphere:
                    properties:
                      failureDomains:
                        items:
                          properties:
                            server:
                              anyOf:
                              - format: ipv4
                              - format: ipv6
                              - format: hostname
                      nodeNetworking:
                        properties:
                          external:
                            properties:
                              excludeNetworkSubnetCidr:
                                items:
                                  format: cidr
                              networkSubnetCidr:
                                items:
                                  format: cidr
                          internal:
                            properties:
                              excludeNetworkSubnetCidr:
                                items:
                                  format: cidr
                              networkSubnetCidr:
                                items:
                                  format: cidr
                      vcenters:
                        items:
                          properties:
                            server:
                              anyOf:
                              - format: ipv4
                              - format: ipv6
                              - format: hostname
