apiVersion: apiextensions.k8s.io/v1 # Hack because controller-gen complains if we don't have this
name: "[Custom] MachineConfigPool"
crd: 0000_80_machineconfigpool-TechPreviewNoUpgrade.crd.yaml
tests:
  onCreate:
  - name: Should be able to create a minimal MachineConfigPool
    initial: |
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      spec:
        pinnedImageSets:
          - name: test-pinnedimageset
    expected: |
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      spec:
        pinnedImageSets:
          - name: test-pinnedimageset
