apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    api-approved.openshift.io: https://github.com/openshift/api/pull/527
    api.openshift.io/filename-ordering: "001"
    feature-gate.release.openshift.io/: "true"
  name: clusternetworks.network.openshift.io
spec:
  group: network.openshift.io
  names:
    kind: ClusterNetwork
    listKind: ClusterNetworkList
    plural: clusternetworks
    singular: clusternetwork
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: The primary cluster network CIDR
      jsonPath: .network
      name: Cluster Network
      type: string
    - description: The service network CIDR
      jsonPath: .serviceNetwork
      name: Service Network
      type: string
    - description: The OpenShift SDN network plug-in in use
      jsonPath: .pluginName
      name: Plugin Name
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: |-
          ClusterNetwork was used by OpenShift SDN.
          DEPRECATED: OpenShift SDN is no longer supported and this object is no longer used in
          any way by OpenShift.

          Compatibility level 1: Stable within a major release for a minimum of 12 months or 3 minor releases (whichever is longer).
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          clusterNetworks:
            description: clusterNetworks is a list of ClusterNetwork objects that
              defines the global overlay network's L3 space by specifying a set of
              CIDR and netmasks that the SDN can allocate addresses from.
            items:
              description: ClusterNetworkEntry defines an individual cluster network.
                The CIDRs cannot overlap with other cluster network CIDRs, CIDRs reserved
                for external ips, CIDRs reserved for service networks, and CIDRs reserved
                for ingress ips.
              properties:
                CIDR:
                  description: CIDR defines the total range of a cluster networks
                    address space.
                  pattern: ^(([0-9]|[0-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[0-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])/([0-9]|[12][0-9]|3[0-2])$
                  type: string
                hostSubnetLength:
                  description: hostSubnetLength is the number of bits of the accompanying
                    CIDR address to allocate to each node. eg, 8 would mean that each
                    node would have a /24 slice of the overlay network for its pods.
                  format: int32
                  maximum: 30
                  minimum: 2
                  type: integer
              required:
              - CIDR
              - hostSubnetLength
              type: object
            type: array
          hostsubnetlength:
            description: hostsubnetlength is the number of bits of network to allocate
              to each node. eg, 8 would mean that each node would have a /24 slice
              of the overlay network for its pods
            format: int32
            maximum: 30
            minimum: 2
            type: integer
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          mtu:
            description: mtu is the MTU for the overlay network. This should be 50
              less than the MTU of the network connecting the nodes. It is normally
              autodetected by the cluster network operator.
            format: int32
            maximum: 65536
            minimum: 576
            type: integer
          network:
            description: network is a CIDR string specifying the global overlay network's
              L3 space
            pattern: ^(([0-9]|[0-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[0-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])/([0-9]|[12][0-9]|3[0-2])$
            type: string
          pluginName:
            description: pluginName is the name of the network plugin being used
            type: string
          serviceNetwork:
            description: serviceNetwork is the CIDR range that Service IP addresses
              are allocated from
            pattern: ^(([0-9]|[0-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[0-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])/([0-9]|[12][0-9]|3[0-2])$
            type: string
          vxlanPort:
            description: |-
              vxlanPort sets the VXLAN destination port used by the cluster.
              It is set by the master configuration file on startup and cannot be edited manually.
              Valid values for VXLANPort are integers 1-65535 inclusive and if unset defaults to 4789.
              Changing VXLANPort allows users to resolve issues between openshift SDN and other software trying to use the same VXLAN destination port.
            format: int32
            maximum: 65535
            minimum: 1
            type: integer
        required:
        - clusterNetworks
        - serviceNetwork
        type: object
    served: true
    storage: true
