apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
  name: machines.machine.openshift.io
