apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/MachineAPIMigration: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
  name: machines.machine.openshift.io
spec:
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          status:
            x-kubernetes-validations:
            - fieldPath: .synchronizedGeneration
              message: synchronizedGeneration must not decrease unless authoritativeAPI
                is transitioning from Migrating to another value
              reason: FieldValueInvalid
              rule: '!has(oldSelf.synchronizedGeneration) || (has(self.synchronizedGeneration)
                && self.synchronizedGeneration >= oldSelf.synchronizedGeneration)
                || (oldSelf.authoritativeAPI == ''Migrating'' && self.authoritativeAPI
                != ''Migrating'')'
