apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consolelinks.console.openshift.io
  annotations:
    displayName: ConsoleLinks
    description: Extension for customizing OpenShift web console links
spec:
  scope: Cluster
  group: console.openshift.io
  versions:
  - name: v1
    served: true
    storage: true
  names:
    plural: consolelinks
    singular: consolelink
    kind: ConsoleLink
    listKind: ConsoleLinkList
  additionalPrinterColumns:
  - name: Text
    type: string
    JSONPath: .spec.text
  - name: URL
    type: string
    JSONPath: .spec.href
  - name: Menu
    type: string
    JSONPath: .spec.menu
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}
  "validation":
    "openAPIV3Schema":
      description: ConsoleLink is an extension for customizing OpenShift web console
        links.
      type: object
      required:
      - spec
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: Standard object's metadata.
          type: object
        spec:
          description: ConsoleLinkSpec is the desired console link configuration.
          type: object
          required:
          - href
          - location
          - text
          properties:
            applicationMenu:
              description: applicationMenu holds information about section and icon
                used for the link in the application menu, and it is applicable only
                when location is set to ApplicationMenu.
              type: object
              required:
              - section
              properties:
                imageURL:
                  description: imageUrl is the URL for the icon used in front of the
                    link in the application menu. The URL must be an HTTPS URL or
                    a Data URI. The image should be square and will be shown at 24x24
                    pixels.
                  type: string
                section:
                  description: section is the section of the application menu in which
                    the link should appear.
                  type: string
            href:
              description: href is the absolute secure URL for the link (must use
                https)
              type: string
            location:
              description: location determines which location in the console the link
                will be appended to.
              type: string
            namespaceDashboard:
              description: namespaceDashboard holds information about namespaces in
                which the dashboard link should appear, and it is applicable only
                when location is set to NamespaceDashboard. If not specified, the
                link will appear in all namespaces.
              type: object
              required:
              - namespaces
              properties:
                namespaces:
                  description: namespaces is an array of namespace names in which
                    the dashboard link should appear.
                  type: array
                  items:
                    type: string
            text:
              description: text is the display text for the link
              type: string
