apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    api-approved.openshift.io: https://github.com/openshift/api/pull/1773
    api.openshift.io/filename-cvo-runlevel: "0000_80"
    api.openshift.io/filename-operator: machine-config
    api.openshift.io/filename-ordering: "01"
    feature-gate.release.openshift.io/OnClusterBuild: "true"
  labels:
    openshift.io/operator-managed: ""
  name: machineosbuilds.machineconfiguration.openshift.io
spec:
  group: machineconfiguration.openshift.io
  names:
    kind: MachineOSBuild
    listKind: MachineOSBuildList
    plural: machineosbuilds
    singular: machineosbuild
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Prepared")].status
      name: Prepared
      type: string
    - jsonPath: .status.conditions[?(@.type=="Building")].status
      name: Building
      type: string
    - jsonPath: .status.conditions[?(@.type=="Succeeded")].status
      name: Succeeded
      type: string
    - jsonPath: .status.conditions[?(@.type=="Interrupted")].status
      name: Interrupted
      type: string
    - jsonPath: .status.conditions[?(@.type=="Failed")].status
      name: Failed
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: |-
          MachineOSBuild describes a build process managed and deployed by the MCO
          Compatibility level 1: Stable within a major release for a minimum of 12 months or 3 minor releases (whichever is longer).
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec describes the configuration of the machine os build
            properties:
              desiredConfig:
                description: desiredConfig is the desired config we want to build
                  an image for.
                properties:
                  name:
                    description: name is the name of the rendered MachineConfig object.
                    maxLength: 253
                    pattern: ^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9]))*$
                    type: string
                required:
                - name
                type: object
              machineOSConfig:
                description: machineOSConfig is the config object which the build
                  is based off of
                properties:
                  name:
                    description: name of the MachineOSConfig
                    maxLength: 256
                    minLength: 1
                    pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                    type: string
                required:
                - name
                type: object
              renderedImagePushspec:
                description: |-
                  renderedImagePushspec is set from the MachineOSConfig
                  The format of the image pullspec is:
                  host[:port][/namespace]/name:<tag> or svc_name.namespace.svc[:port]/repository/name:<tag>
                maxLength: 447
                minLength: 1
                type: string
                x-kubernetes-validations:
                - message: the OCI Image name should follow the host[:port][/namespace]/name
                    format, resembling a valid URL without the scheme. Or it must
                    be a valid .svc followed by a port, repository, image name, and
                    tag.
                  rule: self.matches('^([a-zA-Z0-9-]+\\.)+[a-zA-Z0-9-]+(:[0-9]{2,5})?(/[a-zA-Z0-9-_]{1,61})*/[a-zA-Z0-9-_.]+:[a-zA-Z0-9._-]+$')
                    || self.matches('^[^.]+\\.[^.]+\\.svc:\\d+\\/[^\\/]+\\/[^\\/]+:[^\\/]+$')
            required:
            - desiredConfig
            - machineOSConfig
            - renderedImagePushspec
            type: object
            x-kubernetes-validations:
            - message: machineOSBuildSpec is immutable once set
              rule: self == oldSelf
          status:
            description: status describes the lst observed state of this machine os
              build
            properties:
              buildEnd:
                description: buildEnd describes when the build ended.
                format: date-time
                type: string
                x-kubernetes-validations:
                - message: buildEnd is immutable once set
                  rule: self == oldSelf
              buildStart:
                description: buildStart describes when the build started.
                format: date-time
                type: string
                x-kubernetes-validations:
                - message: buildStart is immutable once set
                  rule: self == oldSelf
              builderReference:
                description: BuilderReference describes which ImageBuilder backend
                  to use for this build
                properties:
                  buildPod:
                    description: relatedObjects is a list of objects that are related
                      to the build process.
                    properties:
                      group:
                        description: |-
                          group of the referent.
                          This value should consist of only lowercase alphanumeric characters, hyphens and periods.
                          Example: "", "apps", "build.openshift.io", etc.
                        pattern: ^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                        type: string
                      name:
                        description: name of the referent.
                        maxLength: 256
                        minLength: 1
                        pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                        type: string
                      namespace:
                        description: namespace of the referent.
                        maxLength: 63
                        minLength: 1
                        pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                        type: string
                      resource:
                        description: |-
                          resource of the referent.
                          This value should consist of only lowercase alphanumeric characters and hyphens.
                          Example: "deployments", "deploymentconfigs", "pods", etc.
                        pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                        type: string
                    required:
                    - group
                    - name
                    - resource
                    type: object
                  imageBuilderType:
                    description: ImageBuilderType describes the image builder set
                      in the MachineOSConfig
                    type: string
                type: object
                x-kubernetes-validations:
                - message: buildPod is required when imageBuilderType is PodImageBuilder,
                    and forbidden otherwise
                  rule: 'has(self.imageBuilderType) && self.imageBuilderType == ''PodImageBuilder''
                    ?  has(self.buildPod) : !has(self.buildPod)'
              conditions:
                description: |-
                  conditions are state related conditions for the build. Valid types are:
                  Prepared, Building, Failed, Interrupted, and Succeeded
                  once a Build is marked as Failed, no future conditions can be set. This is enforced by the MCO.
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              finalImagePullspec:
                description: finalImagePushSpec describes the fully qualified pushspec
                  produced by this build that the final image can be. Must end with
                  a valid '@sha256:<digest>' suffix, where '<digest>' is 64 hexadecimal
                  characters long
                type: string
                x-kubernetes-validations:
                - message: the OCI Image reference must end with a valid '@sha256:<digest>'
                    suffix, where '<digest>' is 64 hexadecimal characters long
                  rule: ((self.split('@').size() == 2 && self.split('@')[1].matches('^sha256:[a-f0-9]{64}$')))
              relatedObjects:
                description: relatedObjects is a list of objects that are related
                  to the build process.
                items:
                  description: ObjectReference contains enough information to let
                    you inspect or modify the referred object.
                  properties:
                    group:
                      description: |-
                        group of the referent.
                        This value should consist of only lowercase alphanumeric characters, hyphens and periods.
                        Example: "", "apps", "build.openshift.io", etc.
                      pattern: ^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                      type: string
                    name:
                      description: name of the referent.
                      maxLength: 256
                      minLength: 1
                      pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                      type: string
                    namespace:
                      description: namespace of the referent.
                      maxLength: 63
                      minLength: 1
                      pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                      type: string
                    resource:
                      description: |-
                        resource of the referent.
                        This value should consist of only lowercase alphanumeric characters and hyphens.
                        Example: "deployments", "deploymentconfigs", "pods", etc.
                      pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                      type: string
                  required:
                  - group
                  - name
                  - resource
                  type: object
                maxItems: 10
                type: array
                x-kubernetes-list-map-keys:
                - name
                - resource
                x-kubernetes-list-type: map
            required:
            - buildStart
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
