package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE
var map_KMSPlugin = map[string]string{
	"":         "KMSPlugin defines how the platform runs a KMS encryption provider plugin sidecar. A KMS provider operator installed via OLM reconciles provider-specific configuration and publishes the container runtime configuration in status.runtime.\n\nCompatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.",
	"metadata": "metadata is the standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata",
	"spec":     "spec is reserved for future use. Operators publish runtime configuration in status.runtime.",
	"status":   "status is the most recently observed status of the KMSPlugin.",
}

func (KMSPlugin) SwaggerDoc() map[string]string {
	return map_KMSPlugin
}

var map_KMSPluginConfigMapReference = map[string]string{
	"":     "KMSPluginConfigMapReference references a ConfigMap in the same namespace as the KMSPlugin.",
	"name": "name is the metadata.name of the referenced ConfigMap. The name must be a valid DNS subdomain name: it must contain no more than 253 characters, contain only lowercase alphanumeric characters, '-' or '.', and start and end with an alphanumeric character.",
}

func (KMSPluginConfigMapReference) SwaggerDoc() map[string]string {
	return map_KMSPluginConfigMapReference
}

var map_KMSPluginList = map[string]string{
	"":         "KMSPluginList contains a list of KMSPlugins.\n\nCompatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.",
	"metadata": "metadata is the standard list's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata",
	"items":    "items is the list of KMSPlugins.",
}

func (KMSPluginList) SwaggerDoc() map[string]string {
	return map_KMSPluginList
}

var map_KMSPluginRuntime = map[string]string{
	"":           "KMSPluginRuntime describes the container configuration for a KMS plugin sidecar. The platform injects -listen-address and manages lifecycle, resources, security context, and mounting Secrets and ConfigMaps from the operator namespace at well-known injection points. Operators must not set -listen-address in args, either as -listen-address=<path> or as a separate -listen-address flag.",
	"image":      "image is the digest-pinned OCI image for the KMS plugin.\n\nThe image must be a fully qualified OCI image pull spec with a SHA256 digest. The format is: host[:port][/namespace]/name@sha256:<digest> where the digest must be 64 characters long and consist only of lowercase hexadecimal characters, a-f and 0-9. The total length must be between 75 and 447 characters.\n\nShort names (e.g., \"vault-plugin\" or \"hashicorp/vault-plugin\") are not allowed. The registry hostname must be included and must contain at least one dot. Image tags (e.g., \":latest\", \":v1.0.0\") are not allowed.",
	"args":       "args are the command-line arguments passed to the KMS plugin container. The platform prepends -listen-address=<uds-path> before these arguments. Arguments may reference credential files mounted by the platform at well-known injection points under /var/run/kms/ from Secrets and ConfigMaps in the operator namespace.",
	"secrets":    "secrets lists Secrets in the same namespace as the KMSPlugin that the platform mounts at well-known injection points under /var/run/kms/secrets/. Plugin arguments may reference files from these mounted Secrets. When omitted, no Secrets are mounted.",
	"configMaps": "configMaps lists ConfigMaps in the same namespace as the KMSPlugin that the platform mounts at well-known injection points under /var/run/kms/config/. Plugin arguments may reference files from these mounted ConfigMaps. When omitted, no ConfigMaps are mounted.",
}

func (KMSPluginRuntime) SwaggerDoc() map[string]string {
	return map_KMSPluginRuntime
}

var map_KMSPluginSecretReference = map[string]string{
	"":     "KMSPluginSecretReference references a Secret in the same namespace as the KMSPlugin.",
	"name": "name is the metadata.name of the referenced Secret. The name must be a valid DNS subdomain name: it must contain no more than 253 characters, contain only lowercase alphanumeric characters, '-' or '.', and start and end with an alphanumeric character.",
}

func (KMSPluginSecretReference) SwaggerDoc() map[string]string {
	return map_KMSPluginSecretReference
}

var map_KMSPluginSpec = map[string]string{
	"": "KMSPluginSpec is reserved for future use.",
}

func (KMSPluginSpec) SwaggerDoc() map[string]string {
	return map_KMSPluginSpec
}

var map_KMSPluginStatus = map[string]string{
	"":        "KMSPluginStatus defines the observed status of KMSPlugin.",
	"runtime": "runtime describes how the platform should run the KMS plugin sidecar. The KMS provider operator must populate this before the platform can deploy the plugin. When omitted, the platform cannot proceed with KMS encryption.",
}

func (KMSPluginStatus) SwaggerDoc() map[string]string {
	return map_KMSPluginStatus
}

// AUTO-GENERATED FUNCTIONS END HERE
