package v1alpha1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// +genclient
// +genclient:nonNamespaced
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:resource:path=bgpvipconfigs,scope=Cluster
// +kubebuilder:subresource:status
// +kubebuilder:validation:XValidation:rule="self.metadata.name == 'cluster'",message="bgpvipconfig is a singleton; metadata.name must be 'cluster'"
// +openshift:api-approved.openshift.io=https://github.com/openshift/api/pull/2972
// +openshift:file-pattern=cvoRunLevel=0000_80,operatorName=machine-config,operatorOrdering=01
// +openshift:enable:FeatureGate=BGPBasedVIPManagement
// +openshift:compatibility-gen:level=4

// BGPVIPConfig carries the BGP peering configuration for BGP-based VIP
// management (enhancement openshift/enhancements#1982). It is a singleton
// named "cluster", generated by the installer from
// platform.baremetal.bgpVIPConfig in the install-config, and may be edited
// day-2 to reconfigure peering.
//
// Compatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.
type BGPVIPConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// spec is the desired BGP VIP peering configuration.
	// +required
	Spec BGPVIPConfigSpec `json:"spec"`
	// status reports the consumers' progress applying the configuration.
	// +optional
	Status BGPVIPConfigStatus `json:"status,omitempty"`
}

// BGPVIPConfigSpec describes the BGP peering used to advertise the API and
// Ingress VIPs.
type BGPVIPConfigSpec struct {
	// localASN is the autonomous system number the cluster's FRR instances
	// run under. Must be between 1 and 4294967295 (int64 because valid ASNs
	// exceed int32 range).
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=4294967295
	// +required
	LocalASN int64 `json:"localASN"`

	// defaultPeers are the BGP peers every node establishes sessions with,
	// unless the node is named in hostOverrides.
	// +listType=map
	// +listMapKey=peerAddress
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=16
	// +required
	DefaultPeers []BGPVIPPeer `json:"defaultPeers"`

	// communities are BGP community strings attached to the VIP
	// advertisements: "n:n" classic communities (RFC 1997) where each
	// segment is a 16-bit value between 0 and 65535, or "n:n:n" large
	// communities (RFC 8092) where each segment is a 32-bit value between
	// 0 and 4294967295. When omitted, no communities are attached. Each
	// entry must be colon-separated decimal numbers, at most 32 characters
	// long.
	// +listType=atomic
	// +kubebuilder:validation:MaxItems=8
	// +kubebuilder:validation:items:MaxLength=32
	// +kubebuilder:validation:items:Pattern=`^\d+:\d+(:\d+)?$`
	// +kubebuilder:validation:items:XValidation:rule="self.split(':').size() == 2 ? self.split(':').all(s, s.size() <= 5 && int(s) <= 65535) : self.split(':').all(s, s.size() <= 10 && int(s) <= 4294967295)",message="classic community (n:n) segments must be between 0 and 65535; large community (n:n:n) segments must be between 0 and 4294967295"
	// +optional
	Communities []string `json:"communities,omitempty"`

	// hostOverrides replaces (does not merge with) defaultPeers for the
	// named nodes. Only the per-node peer file rendered by the
	// machine-config-operator consumes overrides; the cluster-wide session
	// configuration rendered by the cluster-network-operator uses
	// defaultPeers. When omitted, all nodes use defaultPeers.
	// +listType=map
	// +listMapKey=hostname
	// +kubebuilder:validation:MaxItems=256
	// +optional
	HostOverrides []BGPVIPHostPeers `json:"hostOverrides,omitempty"`
}

// BGPVIPHostPeers is a per-node replacement peer list.
type BGPVIPHostPeers struct {
	// hostname of the node this override applies to, as an RFC 1123
	// subdomain (matched against the hostname resolved on the node).
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=253
	// +kubebuilder:validation:XValidation:rule="self.matches('^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$')",message="hostname must be an RFC 1123 subdomain"
	// +required
	Hostname string `json:"hostname"`

	// peers replaces defaultPeers for this node.
	// +listType=map
	// +listMapKey=peerAddress
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=16
	// +required
	Peers []BGPVIPPeer `json:"peers"`
}

// BFDMode enables or disables BFD for a BGP session.
// +kubebuilder:validation:Enum:=Enabled;Disabled;""
type BFDMode string

const (
	// BFDModeEnabled backs the session with BFD fast failure detection.
	BFDModeEnabled BFDMode = "Enabled"
	// BFDModeDisabled runs the session without BFD.
	BFDModeDisabled BFDMode = "Disabled"
)

// EBGPMultiHopMode enables or disables eBGP multihop for a BGP session.
// +kubebuilder:validation:Enum:=Enabled;Disabled;""
type EBGPMultiHopMode string

const (
	// EBGPMultiHopModeEnabled allows the session to cross multiple hops.
	EBGPMultiHopModeEnabled EBGPMultiHopMode = "Enabled"
	// EBGPMultiHopModeDisabled requires the peer to be directly connected.
	EBGPMultiHopModeDisabled EBGPMultiHopMode = "Disabled"
)

// BGPVIPPasswordSecret references a Secret in the openshift-config
// namespace by name.
type BGPVIPPasswordSecret struct {
	// name is the metadata.name of the referenced Secret in the
	// openshift-config namespace. Must be an RFC 1123 subdomain.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=253
	// +kubebuilder:validation:XValidation:rule="self.matches('^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$')",message="name must be an RFC 1123 subdomain"
	// +required
	Name string `json:"name"`
}

// BGPVIPPeer describes one BGP neighbor.
// +kubebuilder:validation:XValidation:rule="!(has(self.holdTimeSeconds) && has(self.keepaliveTimeSeconds)) || self.holdTimeSeconds == 0 || self.keepaliveTimeSeconds == 0 || self.holdTimeSeconds >= 3 * self.keepaliveTimeSeconds",message="holdTimeSeconds must be at least 3 times keepaliveTimeSeconds"
type BGPVIPPeer struct {
	// peerAddress is the IP address of the BGP neighbor (IPv4 or IPv6); the
	// session's address family follows the address family of this value.
	// +kubebuilder:validation:MaxLength=45
	// +kubebuilder:validation:XValidation:rule="isIP(self)",message="peerAddress must be a valid IP address"
	// +required
	PeerAddress string `json:"peerAddress"`

	// peerASN is the autonomous system number of the neighbor. Must be
	// between 1 and 4294967295.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=4294967295
	// +required
	PeerASN int64 `json:"peerASN"`

	// passwordSecret references the Secret carrying the TCP MD5 password
	// (RFC 2385) for the session. The Secret must be of type
	// kubernetes.io/basic-auth, live in the openshift-config namespace, and
	// carry the password in its "password" key (at most 80 bytes, the
	// kernel's TCP MD5 limit). Passwords are never stored in this API; the
	// consumers resolve the reference. When omitted, the session is
	// unauthenticated.
	// +optional
	PasswordSecret BGPVIPPasswordSecret `json:"passwordSecret,omitempty,omitzero"`

	// port is the TCP port of the BGP session. When omitted, port 179 is
	// used; this default is applied by the consumers and is subject to
	// change over time.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=65535
	// +optional
	Port int32 `json:"port,omitempty"`

	// bfd determines whether the session is backed by BFD fast failure
	// detection. Allowed values are "Enabled", "Disabled" and omitted. When
	// omitted, BFD is disabled; this default is subject to change over time.
	// +optional
	BFD BFDMode `json:"bfd,omitempty"`

	// ebgpMultiHop determines whether the session may cross multiple hops.
	// Allowed values are "Enabled", "Disabled" and omitted. When omitted,
	// multihop is disabled; this default is subject to change over time.
	// +optional
	EBGPMultiHop EBGPMultiHopMode `json:"ebgpMultiHop,omitempty"`

	// holdTimeSeconds is the BGP hold time in seconds, between 0 and 65535.
	// When omitted or 0, the FRR default is used; this is subject to change
	// over time.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=65535
	// +optional
	HoldTimeSeconds int32 `json:"holdTimeSeconds,omitempty"`

	// keepaliveTimeSeconds is the BGP keepalive interval in seconds,
	// between 0 and 65535. When omitted or 0, the FRR default is used; this
	// is subject to change over time.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=65535
	// +optional
	KeepaliveTimeSeconds int32 `json:"keepaliveTimeSeconds,omitempty"`
}

// BGPVIPConfigStatus reports the consumers' progress applying the spec.
type BGPVIPConfigStatus struct {
	// observedGeneration is the generation most recently processed by the
	// machine-config-operator.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// conditions reports the state of applying the configuration. Known
	// condition types are "Rendered" (the machine-config-operator has
	// rendered the per-node peer configuration) and "SessionsConfigured"
	// (the cluster-network-operator has applied the session configuration).
	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

const (
	// BGPVIPConfigRendered is set by the machine-config-operator when the
	// per-node peer configuration reflecting the current spec generation
	// has been rendered.
	BGPVIPConfigRendered = "Rendered"
	// BGPVIPConfigSessionsConfigured is set by the cluster-network-operator
	// when the FRR session configuration reflecting the current spec has
	// been rendered for application.
	BGPVIPConfigSessionsConfigured = "SessionsConfigured"
)

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +openshift:compatibility-gen:level=4

// BGPVIPConfigList is a list of BGPVIPConfig resources.
//
// Compatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.
type BGPVIPConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`
	Items           []BGPVIPConfig `json:"items"`
}
