package v1alpha1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// +genclient
// +genclient:nonNamespaced
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:resource:path=bgpvipconfigs,scope=Cluster
// +kubebuilder:subresource:status
// +kubebuilder:metadata:labels=openshift.io/operator-managed=
// +kubebuilder:validation:XValidation:rule="self.metadata.name == 'cluster'",message="bgpvipconfig is a singleton, .metadata.name must be 'cluster'"
// +openshift:api-approved.openshift.io=https://github.com/openshift/api/pull/2972
// +openshift:file-pattern=cvoRunLevel=0000_80,operatorName=machine-config,operatorOrdering=01
// +openshift:enable:FeatureGate=BGPBasedVIPManagement
// +openshift:compatibility-gen:level=4

// BGPVIPConfig carries the BGP peering configuration for BGP-based VIP
// management (enhancement openshift/enhancements#1982). It is a singleton
// named "cluster", generated by the installer from
// platform.baremetal.bgpVIPConfig in the install-config, and may be edited
// day-2 to reconfigure peering.
//
// Compatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.
type BGPVIPConfig struct {
	metav1.TypeMeta `json:",inline"`

	// metadata is the standard object's metadata.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	// +required
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// spec is the desired BGP VIP peering configuration.
	// +required
	Spec BGPVIPConfigSpec `json:"spec,omitempty,omitzero"`

	// status reports the consumers' progress applying the configuration.
	// +optional
	Status BGPVIPConfigStatus `json:"status,omitempty,omitzero"`
}

// BGPVIPConfigSpec describes the BGP peering used to advertise the API and
// Ingress VIPs.
type BGPVIPConfigSpec struct {
	// localASN is the autonomous system number the cluster's FRR instances
	// run under. Must be between 1 and 4294967295 (int64 because valid ASNs
	// exceed int32 range).
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=4294967295
	// +required
	LocalASN int64 `json:"localASN,omitempty"`

	// defaultPeers are the BGP peers every node establishes sessions with,
	// unless the node is named in hostOverrides. Must contain between 1 and
	// 16 peers, unique by peerAddress.
	// +listType=map
	// +listMapKey=peerAddress
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=16
	// +required
	DefaultPeers []BGPVIPPeer `json:"defaultPeers,omitempty"`

	// communities are BGP community strings attached to the VIP
	// advertisements: "n:n" classic communities (RFC 1997) where each
	// segment is a 16-bit value between 0 and 65535, or "n:n:n" large
	// communities (RFC 8092) where each segment is a 32-bit value between
	// 0 and 4294967295. When omitted, no communities are attached. Each
	// entry must be colon-separated decimal numbers without leading zeros,
	// between 3 and 32 characters long; when set, between 1 and 8 entries.
	// +listType=atomic
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=8
	// +kubebuilder:validation:items:MinLength=3
	// +kubebuilder:validation:items:MaxLength=32
	// +kubebuilder:validation:items:Pattern=`^(0|[1-9]\d*)(:(0|[1-9]\d*)){1,2}$`
	// +kubebuilder:validation:items:XValidation:rule="self.split(':').size() == 2 ? self.split(':').all(s, s.size() <= 5 && int(s) <= 65535) : self.split(':').all(s, s.size() <= 10 && int(s) <= 4294967295)",message="classic community (n:n) segments must be between 0 and 65535; large community (n:n:n) segments must be between 0 and 4294967295"
	// +optional
	Communities []string `json:"communities,omitempty"`

	// hostOverrides replaces (does not merge with) defaultPeers for the
	// named nodes. Only the per-node peer file rendered by the
	// machine-config-operator consumes overrides; the cluster-wide session
	// configuration rendered by the cluster-network-operator uses
	// defaultPeers. When omitted, all nodes use defaultPeers; when set,
	// between 1 and 256 entries, unique by hostname.
	// +listType=map
	// +listMapKey=hostname
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=256
	// +optional
	HostOverrides []BGPVIPHostPeers `json:"hostOverrides,omitempty"`
}

// BGPVIPHostPeers is a per-node replacement peer list.
type BGPVIPHostPeers struct {
	// hostname of the node this override applies to, as a non-empty RFC
	// 1123 subdomain of at most 253 characters with dot-separated labels of
	// at most 63 characters each. It is compared verbatim against
	// the hostname the node resolves for itself (as rendered into the
	// per-node peer file), so a short name and its fully qualified form are
	// distinct entries and only the exact match applies.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=253
	// +kubebuilder:validation:XValidation:rule="self.matches('^[a-z0-9]([-a-z0-9]{0,61}[a-z0-9])?(\\\\.[a-z0-9]([-a-z0-9]{0,61}[a-z0-9])?)*$')",message="hostname must be an RFC 1123 subdomain with labels of at most 63 characters"
	// +required
	Hostname string `json:"hostname,omitempty"`

	// peers replaces defaultPeers for this node. Must contain between 1 and
	// 16 peers, unique by peerAddress.
	// +listType=map
	// +listMapKey=peerAddress
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=16
	// +required
	Peers []BGPVIPPeer `json:"peers,omitempty"`
}

// BFDMode enables or disables BFD for a BGP session.
// +kubebuilder:validation:Enum:=Enabled;Disabled
type BFDMode string

const (
	// BFDModeEnabled backs the session with BFD fast failure detection.
	BFDModeEnabled BFDMode = "Enabled"
	// BFDModeDisabled runs the session without BFD.
	BFDModeDisabled BFDMode = "Disabled"
)

// EBGPMultiHopMode enables or disables eBGP multihop for a BGP session.
// +kubebuilder:validation:Enum:=Enabled;Disabled
type EBGPMultiHopMode string

const (
	// EBGPMultiHopModeEnabled allows the session to cross multiple hops.
	EBGPMultiHopModeEnabled EBGPMultiHopMode = "Enabled"
	// EBGPMultiHopModeDisabled requires the peer to be directly connected.
	EBGPMultiHopModeDisabled EBGPMultiHopMode = "Disabled"
)

// BGPVIPPasswordSecret references a Secret in the openshift-config
// namespace by name.
type BGPVIPPasswordSecret struct {
	// name is the metadata.name of the referenced Secret in the
	// openshift-config namespace. Must be a non-empty RFC 1123 subdomain of
	// at most 253 characters with dot-separated labels of at most 63
	// characters each.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=253
	// +kubebuilder:validation:XValidation:rule="self.matches('^[a-z0-9]([-a-z0-9]{0,61}[a-z0-9])?(\\\\.[a-z0-9]([-a-z0-9]{0,61}[a-z0-9])?)*$')",message="name must be an RFC 1123 subdomain with labels of at most 63 characters"
	// +required
	Name string `json:"name,omitempty"`
}

// BGPVIPPeer describes one BGP peer.
// +kubebuilder:validation:XValidation:rule="!(has(self.holdTimeSeconds) && has(self.keepaliveTimeSeconds)) || self.holdTimeSeconds == 0 || self.keepaliveTimeSeconds == 0 || self.holdTimeSeconds >= 3 * self.keepaliveTimeSeconds",message="holdTimeSeconds must be at least 3 times keepaliveTimeSeconds"
type BGPVIPPeer struct {
	// peerAddress is the IP address of the BGP peer (IPv4 or IPv6) in
	// canonical form (lowercase, no leading zeros, IPv6 zero-compressed),
	// between 2 and 45 characters; the session's address family follows the
	// address family of this value. Canonical form is required so that two
	// spellings of one address cannot form duplicate peers.
	// +kubebuilder:validation:MinLength=2
	// +kubebuilder:validation:MaxLength=45
	// +kubebuilder:validation:XValidation:rule="isIP(self) && ip.isCanonical(self)",message="peerAddress must be a valid IP address in canonical form"
	// +required
	PeerAddress string `json:"peerAddress,omitempty"`

	// peerASN is the autonomous system number of the peer. Must be
	// between 1 and 4294967295.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=4294967295
	// +required
	PeerASN int64 `json:"peerASN,omitempty"`

	// passwordSecret references the Secret carrying the TCP MD5 password
	// (RFC 2385) for the session. The Secret must be of type
	// kubernetes.io/basic-auth, live in the openshift-config namespace, and
	// carry the password in its "password" key (at most 80 bytes, the
	// kernel's TCP MD5 limit). The Secret type, key, and size requirements
	// are not validated by the API server; the consumers validate them when
	// resolving the reference and must never surface the Secret contents in
	// status, events, or logs. Passwords are never stored in this API. When
	// omitted, the session is unauthenticated.
	// +optional
	PasswordSecret BGPVIPPasswordSecret `json:"passwordSecret,omitempty,omitzero"`

	// port is the TCP port of the BGP session, between 1 and 65535. When
	// omitted, port 179 is used; this default is applied by the consumers
	// and is subject to change over time.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=65535
	// +optional
	Port int32 `json:"port,omitempty"`

	// bfd determines whether the session is backed by BFD fast failure
	// detection. When set to "Enabled", a BFD session is established with
	// the peer and BGP reacts to BFD failure detection. When set to
	// "Disabled", failure detection relies on the BGP hold timer alone.
	// When omitted, BFD is disabled; this default is subject to change over
	// time.
	// +optional
	BFD BFDMode `json:"bfd,omitempty"`

	// ebgpMultiHop determines whether the session may cross multiple hops.
	// When set to "Enabled", the session may be established with a peer
	// several router hops away. When set to "Disabled", the peer must be
	// directly connected. When omitted, multihop is disabled; this default
	// is subject to change over time.
	// +optional
	EBGPMultiHop EBGPMultiHopMode `json:"ebgpMultiHop,omitempty"`

	// holdTimeSeconds is the BGP hold time in seconds, either 0 or between
	// 3 and 65535 (RFC 4271 requires a hold time of 0 or at least 3
	// seconds). When omitted or 0, the FRR default is used; this is subject
	// to change over time. When both holdTimeSeconds and
	// keepaliveTimeSeconds are set and non-zero, holdTimeSeconds must be at
	// least 3 times keepaliveTimeSeconds.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=65535
	// +kubebuilder:validation:XValidation:rule="self == 0 || self >= 3",message="holdTimeSeconds must be 0 or at least 3"
	// +optional
	HoldTimeSeconds *int32 `json:"holdTimeSeconds,omitempty"`

	// keepaliveTimeSeconds is the BGP keepalive interval in seconds,
	// between 0 and 65535. When omitted or 0, the FRR default is used; this
	// is subject to change over time. When both holdTimeSeconds and
	// keepaliveTimeSeconds are set and non-zero, holdTimeSeconds must be at
	// least 3 times keepaliveTimeSeconds.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=65535
	// +optional
	KeepaliveTimeSeconds *int32 `json:"keepaliveTimeSeconds,omitempty"`
}

// BGPVIPConfigStatus reports the consumers' progress applying the spec.
// +kubebuilder:validation:MinProperties=1
type BGPVIPConfigStatus struct {
	// conditions reports the state of processing the configuration; when
	// set, between 1 and 8 entries. Known
	// condition types are "Rendered" (the machine-config-operator has
	// rendered the per-node peer configuration) and "SessionsConfigured"
	// (the cluster-network-operator has rendered the FRR session
	// configuration for application). SessionsConfigured does not assert
	// that the generated FRRConfiguration was accepted by the frr-k8s
	// admission webhook or applied on the nodes.
	// +listType=map
	// +listMapKey=type
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=8
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// observedGeneration is the generation most recently processed by the
	// machine-config-operator, at least 1 when set. The
	// cluster-network-operator's progress is reported by the
	// observedGeneration of the "SessionsConfigured" condition instead; it
	// does not write this field.
	// +kubebuilder:validation:Minimum=1
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
}

const (
	// BGPVIPConfigRendered is set by the machine-config-operator when the
	// per-node peer configuration reflecting the current spec generation
	// has been rendered.
	BGPVIPConfigRendered = "Rendered"
	// BGPVIPConfigSessionsConfigured is set by the cluster-network-operator
	// when the FRR session configuration reflecting the current spec has
	// been rendered for application. It does not assert admission-webhook
	// acceptance or on-node application of the generated FRRConfiguration.
	BGPVIPConfigSessionsConfigured = "SessionsConfigured"
)

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +openshift:compatibility-gen:level=4

// BGPVIPConfigList is a list of BGPVIPConfig resources.
//
// Compatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.
type BGPVIPConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`
	Items           []BGPVIPConfig `json:"items"`
}
