// +build !ignore_autogenerated

// Code generated by openshift-compatibility-gen. DO NOT EDIT.

package v1alpha1

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *GenericOperatorConfig) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *GenericOperatorConfig) Exposed() bool {
	return true
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *ImageContentSourcePolicy) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *ImageContentSourcePolicy) Exposed() bool {
	return true
}

// CompatibilityLevel is an autogenerated function, returning the OpenShift API compatibility level.
// It is controlled by the "openshift:compatibility-gen:level" tag in types.go.
func (in *ImageContentSourcePolicyList) CompatibilityLevel() (level int) {
	return 4
}

// Exposed is an autogenerated function, returning the true if the type is exposed as an OpenShift API.
// It is controlled by the "openshift:compatibility-gen:exposed" tag in types.go.
func (in *ImageContentSourcePolicyList) Exposed() bool {
	return true
}
