// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CriticalResource) DeepCopyInto(out *CriticalResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CriticalResource.
func (in *CriticalResource) DeepCopy() *CriticalResource {
	if in == nil {
		return nil
	}
	out := new(CriticalResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CriticalResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CriticalResourceCriteria) DeepCopyInto(out *CriticalResourceCriteria) {
	*out = *in
	if in.Finalizer != nil {
		in, out := &in.Finalizer, &out.Finalizer
		*out = new(FinalizerCriticalResourceCriteria)
		**out = **in
	}
	if in.SpecificResource != nil {
		in, out := &in.SpecificResource, &out.SpecificResource
		*out = new(SpecificResourceCriticalResourceCriteria)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CriticalResourceCriteria.
func (in *CriticalResourceCriteria) DeepCopy() *CriticalResourceCriteria {
	if in == nil {
		return nil
	}
	out := new(CriticalResourceCriteria)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CriticalResourceList) DeepCopyInto(out *CriticalResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CriticalResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CriticalResourceList.
func (in *CriticalResourceList) DeepCopy() *CriticalResourceList {
	if in == nil {
		return nil
	}
	out := new(CriticalResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CriticalResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CriticalResourceProvider) DeepCopyInto(out *CriticalResourceProvider) {
	*out = *in
	out.GroupResource = in.GroupResource
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CriticalResourceProvider.
func (in *CriticalResourceProvider) DeepCopy() *CriticalResourceProvider {
	if in == nil {
		return nil
	}
	out := new(CriticalResourceProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CriticalResourceSpec) DeepCopyInto(out *CriticalResourceSpec) {
	*out = *in
	out.Provider = in.Provider
	if in.Criteria != nil {
		in, out := &in.Criteria, &out.Criteria
		*out = make([]CriticalResourceCriteria, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CriticalResourceSpec.
func (in *CriticalResourceSpec) DeepCopy() *CriticalResourceSpec {
	if in == nil {
		return nil
	}
	out := new(CriticalResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CriticalResourceStatus) DeepCopyInto(out *CriticalResourceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CriticalResourceStatus.
func (in *CriticalResourceStatus) DeepCopy() *CriticalResourceStatus {
	if in == nil {
		return nil
	}
	out := new(CriticalResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinalizerCriticalResourceCriteria) DeepCopyInto(out *FinalizerCriticalResourceCriteria) {
	*out = *in
	out.GroupResource = in.GroupResource
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinalizerCriticalResourceCriteria.
func (in *FinalizerCriticalResourceCriteria) DeepCopy() *FinalizerCriticalResourceCriteria {
	if in == nil {
		return nil
	}
	out := new(FinalizerCriticalResourceCriteria)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupResource) DeepCopyInto(out *GroupResource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupResource.
func (in *GroupResource) DeepCopy() *GroupResource {
	if in == nil {
		return nil
	}
	out := new(GroupResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecificResourceCriticalResourceCriteria) DeepCopyInto(out *SpecificResourceCriticalResourceCriteria) {
	*out = *in
	out.GroupResource = in.GroupResource
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecificResourceCriticalResourceCriteria.
func (in *SpecificResourceCriticalResourceCriteria) DeepCopy() *SpecificResourceCriticalResourceCriteria {
	if in == nil {
		return nil
	}
	out := new(SpecificResourceCriticalResourceCriteria)
	in.DeepCopyInto(out)
	return out
}
