package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE
var map_DNSNameResolver = map[string]string{
	"":         "DNSNameResolver stores the DNS name resolution information of a DNS name. It is TechPreviewNoUpgrade only.\n\nCompatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.",
	"metadata": "metadata is the standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata",
	"spec":     "spec is the specification of the desired behavior of the DNSNameResolver.",
	"status":   "status is the most recently observed status of the DNSNameResolver.",
}

func (DNSNameResolver) SwaggerDoc() map[string]string {
	return map_DNSNameResolver
}

var map_DNSNameResolverList = map[string]string{
	"":         "DNSNameResolverList contains a list of DNSNameResolvers.\n\nCompatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.",
	"metadata": "metadata is the standard list's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata",
}

func (DNSNameResolverList) SwaggerDoc() map[string]string {
	return map_DNSNameResolverList
}

var map_DNSNameResolverSpec = map[string]string{
	"":     "DNSNameResolverSpec is a desired state description of DNSNameResolver.",
	"name": "name is the DNS name for which the DNS name resolution information will be stored. For a regular DNS name, only the DNS name resolution information of the regular DNS name will be stored. For a wildcard DNS name, the DNS name resolution information of all the DNS names, that matches the wildcard DNS name, will be stored. For a wildcard DNS name, the '*' will match only one label. Additionally, only a single '*' can be used at the beginning of the wildcard DNS name. For example, '*.example.com.' will match 'sub1.example.com.' but won't match 'sub2.sub1.example.com.'",
}

func (DNSNameResolverSpec) SwaggerDoc() map[string]string {
	return map_DNSNameResolverSpec
}

var map_DNSNameResolverStatus = map[string]string{
	"":              "DNSNameResolverStatus defines the observed status of DNSNameResolver.",
	"resolvedNames": "resolvedNames contains a list of matching DNS names and their corresponding IP addresses along with TTL and last DNS lookup time.",
}

func (DNSNameResolverStatus) SwaggerDoc() map[string]string {
	return map_DNSNameResolverStatus
}

var map_DNSNameResolverStatusItem = map[string]string{
	"":                   "DNSNameResolverStatusItem describes the details of a resolved DNS name.",
	"dnsName":            "dnsName is the resolved DNS name matching the name field of DNSNameResolverSpec.",
	"ips":                "ips contains the list of IP addresses associated with the dnsName.",
	"ttlSeconds":         "ttlSeconds is the minimum time-to-live value among all the IP addresses.",
	"lastLookupTime":     "lastLookupTime is the timestamp when the last DNS lookup was completed.",
	"resolutionFailures": "resolutionFailures keeps the count of how many times the DNS resolution failed for the dnsName field. If the DNS resolution succeeds then the field will be set to zero. Upon every failure, the value of the field will be incremented by one. Upon reaching a threshold value, the details about the DNS name will be removed.",
	"conditions":         "conditions provide information about the state of the DNS name.\n\nThese are the supported conditions:\n\n  * Degraded\n  - True if the following conditions are met:\n    * The last DNS name resolution failed.\n  - False if any of those conditions are unsatisfied.",
}

func (DNSNameResolverStatusItem) SwaggerDoc() map[string]string {
	return map_DNSNameResolverStatusItem
}

// AUTO-GENERATED FUNCTIONS END HERE
