apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/: "true"
  name: ingresscontrollers.operator.openshift.io
spec:
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              logging:
                properties:
                  access:
                    properties:
                      destination:
                        properties:
                          syslog:
                            oneOf:
                            - properties:
                                address:
                                  format: ipv4
                            - properties:
                                address:
                                  format: ipv6
              tuningOptions:
                anyOf:
                - properties:
                    maxConnections:
                      enum:
                      - -1
                      - 0
                - properties:
                    maxConnections:
                      format: int32
                      maximum: 2000000
                      minimum: 2000
    subresources:
      scale:
        labelSelectorPath: .status.selector
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.availableReplicas
