apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    feature-gate.release.openshift.io/DNSNameResolver: "true"
  name: dnsnameresolvers.network.openshift.io
spec:
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              resolvedNames:
                items:
                  properties:
                    resolvedAddresses:
                      items:
                        properties:
                          ip:
                            anyOf:
                            - format: ipv4
                            - format: ipv6
